services:
  frontend:
    container_name: frontend
    image: frontend_local_dev
    command: ["pnpm", "vite", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    networks:
      - test_network
  backend:
    container_name: go-recipes
    image: go-recipes
    ports:
      - "8080:8080"
    networks:
      - test_network
networks:
  test_network:
    driver: bridge

